# Generated by Django 2.2.6 on 2020-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200327_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, help_text='头像', max_length=1024, null=True, upload_to='teacher_photo', verbose_name='头像'),
        ),
    ]
