# Generated by Django 2.2.6 on 2020-03-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20200318_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(help_text='关联用户类型', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, default='', help_text='姓名', max_length=128, null=True, verbose_name='姓名')),
                ('photo', models.ImageField(blank=True, help_text='学生头像', max_length=1024, null=True, upload_to='student_photo', verbose_name='学生头像')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'students',
            },
        ),
    ]
