# Generated by Django 2.2.6 on 2020-03-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200320_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(blank=True, default='student', max_length=128, null=True),
        ),
    ]
