# Generated by Django 2.2.6 on 2020-03-26 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(blank=True, help_text='教室号', max_length=64, null=True, unique=True, verbose_name='教室号')),
                ('room_name', models.CharField(default='', help_text='教室名称', max_length=128, verbose_name='教室名称')),
                ('school', models.CharField(blank=True, help_text='学校', max_length=128, null=True, verbose_name='学校')),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '十年级'), (11, '十一年级'), (12, '十二年级')], default=3, help_text='年级', verbose_name='年级')),
                ('user', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '教室信息',
                'verbose_name_plural': '教室信息',
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('teacher', '老师'), ('student', '学生')], default='', help_text='成员类型', max_length=30, verbose_name='成员类型')),
                ('application_time', models.DateTimeField(default=datetime.datetime.now, help_text='申请时间', verbose_name='申请时间')),
                ('application_type', models.CharField(choices=[('link', '链接邀请'), ('seacher', '搜索'), ('creater', '创建者')], default='', help_text='申请方式', max_length=30, verbose_name='申请方式')),
                ('application_result', models.IntegerField(blank=True, choices=[(1, '通过'), (2, '拒绝'), (3, '待审核')], help_text='申请结果', null=True, verbose_name='申请结果')),
                ('status', models.CharField(choices=[('inclass', '在教室'), ('outclass', '不在教室')], default='', help_text='状态', max_length=30, verbose_name='状态')),
                ('group', models.IntegerField(choices=[(0, '未分组'), (1, '一组'), (2, '二组'), (3, '三组'), (4, '四组'), (5, '五组'), (6, '六组'), (7, '七组'), (8, '八组'), (9, '九组'), (10, '十组')], default=0, help_text='分组', verbose_name='分组')),
                ('examine_time', models.DateTimeField(auto_now=True, null=True, verbose_name='审核时间')),
                ('Inviter', models.ForeignKey(blank=True, help_text='邀请人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter_user', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('class_id', models.ForeignKey(blank=True, help_text='教室id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clsroom', to='classroom.ClassRoom', verbose_name='教室id')),
                ('examine_man', models.ForeignKey(blank=True, help_text='审核人员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea1', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
                ('user', models.ForeignKey(blank=True, help_text='人员信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_user', to=settings.AUTH_USER_MODEL, verbose_name='人员信息')),
            ],
            options={
                'verbose_name': '教室成员信息',
                'verbose_name_plural': '教室成员信息',
                'db_table': 'classmember',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(choices=[(0, '未分组'), (1, '一组'), (2, '二组'), (3, '三组'), (4, '四组'), (5, '五组'), (6, '六组'), (7, '七组'), (8, '八组'), (9, '九组'), (10, '十组')], default=0, help_text='分组', verbose_name='分组')),
                ('group_num', models.IntegerField(default=0, help_text='分组人数', verbose_name='分组人数')),
                ('class_id', models.ForeignKey(blank=True, help_text='教室id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='classroom.ClassRoom', verbose_name='教室id')),
                ('members', models.ForeignKey(blank=True, help_text='成员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classmember', to='classroom.ClassMember', verbose_name='成员')),
            ],
            options={
                'verbose_name': '分组表',
                'verbose_name_plural': '分组表',
                'db_table': 'classgroup',
            },
        ),
    ]
