# Generated by Django 2.2.6 on 2020-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='application_result',
            field=models.IntegerField(blank=True, choices=[(1, '通过'), (2, '拒绝'), (3, '待审核')], default=3, help_text='申请结果', null=True, verbose_name='申请结果'),
        ),
    ]
