# Generated by Django 2.2.6 on 2020-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200330_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='group',
            field=models.IntegerField(choices=[(0, '未分组'), (1, '一组'), (2, '二组'), (3, '三组'), (4, '四组'), (5, '五组'), (6, '六组'), (7, '七组'), (8, '八组'), (9, '九组'), (10, '十组'), (11, '老师组')], default=0, help_text='分组', verbose_name='分组'),
        ),
    ]
