# Generated by Django 2.2.6 on 2020-03-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200316_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
