# Generated by Django 2.2.6 on 2020-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200318_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(blank=True, help_text='头像', max_length=1024, null=True, upload_to='StaticPhoto', verbose_name='头像')),
            ],
            options={
                'verbose_name': '静态图片',
                'verbose_name_plural': '静态图片',
            },
        ),
        migrations.CreateModel(
            name='UploadPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(blank=True, help_text='头像', max_length=1024, null=True, upload_to='UploadPhoto', verbose_name='头像')),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
            },
        ),
    ]
